source/visitormanagement/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

source/visitormanagement/visitormanagement/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('visitors/', include('visitors.urls', namespace='visitors')),
    path('companies/', include('companies.urls', namespace='companies')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

source/visitormanagement/visitors/urls.py
from django.urls import path

from . import views

app_name = 'visitors'

urlpatterns = [
    # ex: /visitors/
    path('', views.index, name='index'),
    path('onGetCreate/', views.onGetCreate, name='onGetCreate'),
    path('onPostCreate/', views.onPostCreate, name='onPostCreate'),
    # path('<int:id>', views.onGetEdit, name='onGetEdit'),
    # path('onPostEdit/', views.onPostEdit, name='onPostEdit'),
    path('onPostDelete/<int:id>', views.onPostDelete, name='onPostDelete'),
]

source/visitormanagement/visitors/models.py
from django.db import models
from companies.models import Company
# Create your models here.


class Visitor(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    visitor_name = models.CharField(max_length=191)
    visitor_phone = models.CharField(max_length=15)
    visitor_from = models.CharField(max_length=191)
    purpose_of_visit = models.CharField(max_length=191)
    visit_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    check_in = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    check_out = models.DateTimeField('check_out', blank=True, null=True)
    barcode = models.CharField(max_length=225, blank=True, null=True)
    visitor_image = models.TextField(max_length=10000, blank=True, null=True)

    def __str__(self):
        return self.visitor_name

source/visitormanagement/visitors/views.py
from django.shortcuts import render, redirect
from .models import Visitor
from companies.models import Company
# from djangonautic.companies.models import Company
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.utils.timezone import datetime
from django.core.serializers.json import DjangoJSONEncoder
import json

# Create your views here.


def index(request):
    visitors = Visitor.objects.order_by('-visit_date')
    context = {'visitors': visitors}
    return render(request, 'visitors/index.html', context)


def onGetCreate(request):
    companies = Company.objects.all()
    context = {
        'companies': companies
    }
    return render(request, 'visitors/create.html', context)


def onPostCreate(request):
    response = {}
    if request.method == 'POST':
        visitor_phone = request.POST.get('visitor_phone')
        visitor_name = request.POST.get('visitor_name')
        visitor_from = request.POST.get('visitor_from')
        purpose_of_visit = request.POST.get('purpose_of_visit')
        company_id = request.POST.get('selectedcompanies')
        visitor_image = request.POST.get('visitor_image')

        visitor = Visitor(visitor_phone=visitor_phone,
                          visitor_name=visitor_name, visitor_from=visitor_from, purpose_of_visit=purpose_of_visit, company_id=company_id, visitor_image=visitor_image)
        visitor.save()
        response = {'status': True, 'visitor_id': visitor.pk}
    return JsonResponse(response)


def onPostDelete(request, id):
    if request.method == "GET":
        user = Visitor.objects.get(id=id)
        user.delete()
    return redirect('visitors:index')

source/visitormanagement/visitors/templates/visitors/create.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}


<form id="visitorForm" action="{% url 'visitors:onPostCreate' %}" method="post" autocomplete="off">
    {% csrf_token %}
    <div class="list-group">
        <div class="list-group-item">
            <div class="row">
                <div class="col"><b>create new visitors</b></div>
                <div class="col">
                    <button type="submit" style="float:right;" class="btn btn-primary btn-sm btn-submit">submit</button>
                </div>
            </div>
        </div>
        <div class="list-group-item">
            <div class="row">
                <div class="col-9">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">

                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="visitor_phone" class="col-form-label">visitor_phone</label>
                                        <input type="number" class="form-control column" id="visitor_phone"
                                            name="visitor_phone" min=0,
                                            onKeyPress="if(this.value.length === 10) return false;">
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="visitor_name" class="col-form-label">visitor_name</label>
                                        <input type="text" class="form-control column" id="visitor_name"
                                            name="visitor_name">
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="visitor_from" class="col-form-label">visitor_from</label>
                                        <input type="text" class="form-control column" id="visitor_from"
                                            name="visitor_from">
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="selectedcompanies" class="col-form-label">company_to_visit</label>
                                        <select class="form-control column" id="selectedcompanies"
                                            name="selectedcompanies">
                                            <option value="0" disabled selected>--SELECT--</option>
                                            {% for company in companies %}
                                            <option value="{{ company.id }}">{{ company.company_name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="purpose_of_visit" class="col-form-label">purpose_of_visit</label>
                                        <input type="text" class="form-control column" id="purpose_of_visit"
                                            name="purpose_of_visit">
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-3">
                    <div class="card webcamcard">
                        <div class="card-body">
                            <div class="row">
                                <a class="d-flex align-items-center text-muted ml-auto camera-on" href="#">
                                    <font color="red"><span data-feather="camera"></span></font>
                                </a>
                                <a class="d-flex align-items-center text-muted mr-auto ml-4 repeat camera-off" href="#">
                                    <font color="red"><span data-feather="camera-off"></span></font>
                                </a>
                            </div>
                            <hr>
                            <div id="webcam"></div>
                            <input type="hidden" id="visitor_image" name="visitor_image">
                            <button type="button" class="btn btn-primary btn-sm btn-block btn-capture mt-2"
                                style="display:none;">capture</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="list-group-item"><a href="{{request.META.HTTP_REFERER}}">Go back</a></div>
    </div>
</form>

<div class="modal fade" id="print-visitor-modal" tabindex="-1" role="dialog"
    aria-labelledby="print-visitor-modalModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-muted"><strong>print-visitor-modal</strong></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary btn-print-visitor">print-visitor</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static 'js/webcamjs/webcam.min.js' %}"></script>
<!-- configure a few settings and attach camera -->
<script>
    $(document).on("click", ".camera-on", function (e) {

        Webcam.set({
            width: 195,
            height: 200,
            image_format: 'jpeg',
            jpeg_quality: 90,
            constraints: {
                width: { exact: 195 },
                height: { exact: 200 }
            }
        });
        Webcam.attach('#webcam');
        $('.btn-capture').css('display', 'block')
        $("video").addClass('card rounded');

    });

    $(document).on("click", ".camera-off", function (e) {
        Webcam.reset();
    });
</script>

<script>
    $(document).on("click", ".btn-capture", function (e) {
        Webcam.snap(function (data_uri) {
            document.getElementById('webcam').innerHTML = '<img class="rounded" src="' + data_uri + '"/>';
            $("#visitor_image").val(data_uri)

            if (!$("#visitor_image").val()) {
                $(".webcamcard").removeClass('border border-danger rounded').addClass('border border-danger rounded');
                $(".webcamcard").attr("tabindex", -1).focus();
                e.preventDefault();
                return false;
            } else {
                $(".webcamcard").removeClass('border border-danger rounded').addClass('border border-success rounded');;
            }

        });
    });
</script>

<script>

    $('#visitorForm').submit(function (e) {
        e.preventDefault();
        e.stopPropagation();

        $('.column').each(function () {
            validateControl($(this), e);
            $('.column').eq(0).focus();
        });

        if (!$("#visitor_image").val()) {
            $(".webcamcard").removeClass('border border-danger rounded').addClass('border border-danger rounded');
            $(".webcamcard").attr("tabindex", -1).focus();
            e.preventDefault();
            return false;
        } else {
            $(".webcamcard").removeClass('border border-danger rounded').addClass('border border-success rounded');
        }

        let html = ''
        html += '<div id="section-to-print" class="offset-3">'
        html += '<table style="width:69%" class="table table-sm table-bordered">'
        html += '<tbody>'

        html += '<tr>'
        html += '<td><h5 class="card-title text-center">visitor info</h5></td>'
        html += '</tr>'

        html += '<tr>'
        html += '<td style="text-align: center; vertical-align: middle;"><img width="100" height="100" class="rounded" src="' + $("#visitor_image").val() + '"/></td>'
        html += '</tr>'

        html += '<tr>'
        html += '<td>visitor_name : ' + $("#visitor_name").val() + '</td>'
        html += '</tr>'

        html += '<tr>'
        html += '<td>visitor_from : ' + $("#visitor_from").val() + '</td>'
        html += '</tr>'

        html += '<tr>'
        html += '<td>company_to_visit : ' + $('#selectedcompanies :selected').text() + '</td>'
        html += '</tr>'

        html += '<tr>'
        html += '<td>purpose_of_visit : ' + $("#purpose_of_visit").val() + '</td>'
        html += '</tr>'

        html += '<tr>'
        html += '<td>checked_in : {% now "f" %}</td>'
        html += '</tr>'

        html += '</tbody>'
        html += '</table></div>'
        $('#print-visitor-modal').find('.modal-body').html(html);

        return false;

        $.ajax({
            data: $(this).serialize(),
            type: $(this).attr('method'),
            url: $(this).attr('action'),
            success: function (response) {
                if (response.visitor_id > 0) {
                    $('#print-visitor-modal').modal({ show: false, backdrop: 'static', keyboard: false })
                    $('#print-visitor-modal').modal('show');
                }
            }
        });
        return false;
    });

</script>

<script>
    $(document).on("click", ".btn-print-visitor", function (e) {
        window.print();
    });
</script>

{% endblock script %}

source/visitormanagement/visitors/templates/visitors/index.html
{% extends 'layout.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static '/lib/datatable/css/dataTables.bootstrap4.min.css' %}">
{% endblock styles %}

{% block content %}

<div class="">
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active mr-auto" id="nav-home-tab" aria-selected="true"><b>visitors list</b></a>
            <a class="nav-item nav-link active" href="{% url 'visitors:onGetCreate' %}">
                <input type="button" value="create new" class="btn btn-outline-primary btn-sm"
                    style="font-weight: bold;" />
            </a>
        </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" role="tabpanel" aria-labelledby="nav-home-tab">
            <br />
            <table id="datatable" class="table table-sm table-hover" style="width:100%;">
                <thead>
                    <tr class="text-dark">
                        <th>
                            <font color="#0C4B33"><small><b>#</b></small></font>
                        </th>
                        <th>
                            <font color="#0C4B33"><small><b>visitor_name</b></small></font>
                        </th>
                        <th>
                            <font color="#0C4B33"><small><b>visitor_phone</b></small></font>
                        </th>
                        <th>
                            <font color="#0C4B33"><small><b>visitor_from</b></small></font>
                        </th>
                        <th>
                            <font color="#0C4B33"><small><b>company_to_visit</b></small></font>
                        </th>
                        <th>
                            <font color="#0C4B33"><small><b>purpose_of_visit</b></small></font>
                        </th>
                        <th>
                            <font color="#0C4B33"><small><b>visit_date</b></small></font>
                        </th>
                        <th>
                            <font color="#0C4B33"><small><b>checked_in</b></small></font>
                        </th>
                        <th>
                            <font color="#0C4B33"><small><b>checked_out</b></small></font>
                        </th>
                        <th>
                            <font color="#0C4B33"><small><b>action</b></small></font>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for visitor in visitors %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ visitor.visitor_name }}</td>
                        <td>{{ visitor.visitor_phone }}</td>
                        <td>{{ visitor.visitor_from }}</td>
                        <td>{{ visitor.company.company_name }}</td>
                        <td>{{ visitor.purpose_of_visit }}</td>
                        <td>{{ visitor.visit_date|date:"Y-m-d" }}</td>
                        <td>{{ visitor.check_in|date:"H:i a" }}</td>
                        <td>{{ visitor.check_out|date:"H:i a" }}</td>
                        <td>
                            <a href="#">link</a> |
                            <a href="{% url 'visitors:onPostDelete' visitor.id %}">delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'lib/datatable/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'lib/datatable/js/dataTables.bootstrap4.min.js' %}"></script>

<script>
    $('#datatable').DataTable();
</script>

{% endblock script %}