source/visitormanagement/companies/urls.py
from django.urls import path

from . import views

app_name = 'companies'

urlpatterns = [
    # ex: /companies/
    path('', views.index, name='index'),
    path('onGetCreate/', views.onGetCreate, name='onGetCreate'),
    path('onPostCreate/', views.onPostCreate, name='onPostCreate'),
    path('<int:id>', views.onGetEdit, name='onGetEdit'),
    path('onPostEdit/<int:id>', views.onPostEdit, name='onPostEdit'),
    path('onPostDelete/<int:id>', views.onPostDelete, name='onPostDelete'),
]

source/visitormanagement/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

source/visitormanagement/visitormanagement/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('visitors/', include('visitors.urls', namespace='visitors')),
    path('companies/', include('companies.urls', namespace='companies')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

source/visitormanagement/companies/models.py
from django.db import models

# Create your models here.


class Company(models.Model):
    company_name = models.CharField(max_length=191, default=None)
    company_phone = models.CharField(max_length=15, default=None)
    company_owner = models.CharField(max_length=191, default=None)
    company_address = models.CharField(max_length=191, default=None)
    contact_person = models.CharField(max_length=191, default=None)
    company_email = models.EmailField(default=None)

    def __str__(self):
        return self.company_name

source/visitormanagement/companies/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core import serializers
from .models import Company
# Create your views here.


def index(request):
    companies = Company.objects.all()
    context = {'companies': companies}
    return render(request, 'companies/index.html', context)


def onGetCreate(request):
    return render(request, 'companies/create.html')


def onPostCreate(request):
    if request.method == 'POST':
        company_name = request.POST.get('company_name')
        company_phone = request.POST.get('company_phone')
        company_email = request.POST.get('company_email')
        company_owner = request.POST.get('company_owner')
        contact_person = request.POST.get('contact_person')
        company_address = request.POST.get('company_address')

        company = Company(company_name=company_name, company_phone=company_phone, company_email=company_email,
                          company_owner=company_owner, contact_person=contact_person, company_address=company_address)
        company.save()
    return redirect('companies:index')


def onGetEdit(request, id):
    companies = Company.objects.get(id=id)
    context = {'companies': companies}
    return render(request, 'companies/edit.html', context)


def onPostEdit(request, id):
    if request.method == "POST":
        company_name = request.POST.get('company_name')
        company_phone = request.POST.get('company_phone')
        company_email = request.POST.get('company_email')
        company_owner = request.POST.get('company_owner')
        contact_person = request.POST.get('contact_person')
        company_address = request.POST.get('company_address')
        Company.objects.filter(id=id).update(company_name=company_name, company_phone=company_phone, company_email=company_email,
                                             company_owner=company_owner, contact_person=contact_person, company_address=company_address)
    return redirect('companies:index')


def onPostDelete(request, id):
    if request.method == "GET":
        user = Company.objects.get(id=id)
        user.delete()
    return redirect('companies:index')

source/visitormanagement/companies/templates/companies/create.html
{% extends 'layout.html' %}

{% block content %}

<form id="companyForm" action="{% url 'companies:onPostCreate' %}" method="post" autocomplete="off">
  {% csrf_token %}
  <div class="list-group">
        <div class="list-group-item">
            <div class="row">
                <div class="col-6"><b>create new company</b></div>
                <div class="col-6"></div>
            </div>
        </div>
        <div class="list-group-item">
            <div class="row">
                <div class="col-12">
                    <div class="row">
                    <div class="col-6">
                            <div class="form-group">
                                <label for="company_name" class="col-form-label">company_name</label>
                                <input type="text" class="form-control column" id="company_name" name="company_name">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="company_phone" class="col-form-label">company_phone</label>
                                <input type="number" class="form-control column" id="company_phone" name="company_phone" min = 1, onKeyPress = "if(this.value.length === 10) return false;">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="company_email" class="col-form-label">company_email</label>
                                <input type="email" class="form-control column" id="company_email" name="company_email">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="company_owner" class="col-form-label">company_owner</label>
                                <input type="text" class="form-control column" id="company_owner" name="company_owner">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="company_address" class="col-form-label">company_address</label>
                                <textarea class="form-control column" id="company_address" rows="3" onKeyPress = "if(this.value.length == 250) return false;" name="company_address"></textarea>
                                <small id="company_address" class="form-text text-muted">max. 250 characters. <font color="blue"><span id="text-remaining"></span></font></small>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="contact_person" class="col-form-label">contact_person</label>
                                <input type="text" class="form-control column" id="contact_person" name="contact_person">
                            </div>
                        </div>                        
                        <div class="col-6">
                            <button type="submit" class="btn btn-primary btn-submit">submit</button>
                        </div>
                    </div>
                </div>
                <div class="col-2"></div>
            </div>
        </div>
        <div class="list-group-item"><a href="{{request.META.HTTP_REFERER}}">Go back</a></div>
    </div>
</form>

{% endblock %}

{% block script %}

<script>
    $(document).on('click', '.btn-submit', function (e) {
        e.preventDefault();
        e.stopPropagation();

        $('.column').each(function(){
            validateControl($(this), e);
            $('.column').eq(0).focus();
        });

        $('#companyForm').submit();
    });
</script>

<script>
    $('#company_address').on('input propertychange paste', function (e) {
        var len = $(this).val().trim().length;
        var str = $(this).val();
        var parts = [];
        var partsize = 250;
        while (str) {
            if (str.length < partsize) {
                var rtext = (partsize - str.length) + " text remaining ";
                parts.push(str);
                break;
            }
            else {
                parts.push(str.substr(0, partsize));
                str = str.substr(partsize);
            }
        }
        document.getElementById('text-remaining').innerHTML = rtext === undefined ? 0 : rtext;
    });
</script>

{% endblock script %}

source/visitormanagement/companies/templates/companies/edit.html
{% extends 'layout.html' %}

{% block content %}

<form od="companyForm" action="{% url 'companies:onPostEdit' companies.id %}" method="post" autocomplete="off">
  {% csrf_token %}
  <div class="list-group">
        <div class="list-group-item">
            <div class="row">
                <div class="col-6"><b>edit company</b></div>
                <div class="col-6"></div>
            </div>
        </div>
        <div class="list-group-item">
            <div class="row">
                <div class="col-12">
                    <div class="row">
                    <div class="col-6">
                            <div class="form-group">
                                <label for="company_name" class="col-form-label">company_name</label>
                                <input type="text" class="form-control" id="company_name" name="company_name" value="{{ companies.company_name }}">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="company_phone" class="col-form-label">company_phone</label>
                                <input type="number" class="form-control" id="company_phone" name="company_phone" min = 1, onKeyPress = "if(this.value.length === 10) return false;" value="{{ companies.company_phone }}">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="company_email" class="col-form-label">company_email</label>
                                <input type="email" class="form-control" id="company_email" name="company_email" value="{{ companies.company_email }}">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="company_owner" class="col-form-label">company_owner</label>
                                <input type="text" class="form-control" id="company_owner" name="company_owner" value="{{ companies.company_owner }}">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="company_address" class="col-form-label">company_address</label>
                                <textarea class="form-control" id="company_address" rows="3" onKeyPress = "if(this.value.length == 250) return false;" name="company_address">{{ companies.company_address }}</textarea>
                                <small id="company_address" class="form-text text-muted">max. 250 characters. <font color="blue"><span id="text-remaining"></span></font></small>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="contact_person" class="col-form-label">contact_person</label>
                                <input type="text" class="form-control" id="contact_person" name="contact_person" value="{{ companies.contact_person }}">
                            </div>
                        </div>                        
                        <div class="col-6">
                            <button type="submit" class="btn btn-primary btn-submit">submit</button>
                        </div>
                    </div>
                </div>
                <div class="col-2"></div>
            </div>
        </div>
        <div class="list-group-item"><a href="{{request.META.HTTP_REFERER}}">Go back</a></div>
    </div>
</form>

{% endblock %}

{% block script %}

<script>
    $(document).on('click', '.btn-submit', function (e) {
        e.preventDefault();
        e.stopPropagation();

        $('.column').each(function(){
            validateControl($(this), e);
            $('.column').eq(0).focus();
        });

        $('#companyForm').submit();
    });
</script>

<script>
    $('#company_address').on('input propertychange paste', function (e) {
        var len = $(this).val().trim().length;
        var str = $(this).val();
        var parts = [];
        var partsize = 250;
        while (str) {
            if (str.length < partsize) {
                var rtext = (partsize - str.length) + " text remaining ";
                parts.push(str);
                break;
            }
            else {
                parts.push(str.substr(0, partsize));
                str = str.substr(partsize);
            }
        }
        document.getElementById('text-remaining').innerHTML = rtext === undefined ? 0 : rtext;
    });
</script>

{% endblock script %}

source/visitormanagement/companies/templates/companies/index.html
{% extends 'layout.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static '/lib/datatable/css/dataTables.bootstrap4.min.css' %}">
{% endblock styles %}

{% block content %}

<div class="">
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active mr-auto" id="nav-home-tab" aria-selected="true"><b>companies list</b></a>
            <a class="nav-item nav-link active" href="{% url 'companies:onGetCreate' %}">
                <input type="button" value="create new" class="btn btn-outline-primary btn-sm"
                    style="font-weight: bold;" />
            </a>
        </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" role="tabpanel" aria-labelledby="nav-home-tab">
            <br />
            <table id="datatable" class="table table-sm table-hover" style="width:100%;">
                <thead>
                    <tr class="text-dark">
                        <th>
                            <font color="#0C4B33"><small><b>#</b></small></font>
                        </th>
                        <th>
                            <font color="#0C4B33"><small><b>company_name</b></small></font>
                        </th>
                        <th>
                            <font color="#0C4B33"><small><b>company_phone</b></small></font>
                        </th>
                        <th>
                            <font color="#0C4B33"><small><b>company_owner</b></small></font>
                        </th>
                        <th>
                            <font color="#0C4B33"><small><b>contact_person</b></small></font>
                        </th>
                        <th>
                            <font color="#0C4B33"><small><b>action</b></small></font>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for company in companies %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ company.company_name }}</td>
                        <td>{{ company.company_phone }}</td>
                        <td>{{ company.company_owner }}</td>
                        <td>{{ company.contact_person }}</td>
                        <td>
                            <a href="{% url 'companies:onGetEdit' company.id %}">edit</a> |
                            <a href="{% url 'companies:onPostDelete' company.id %}">delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'lib/datatable/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'lib/datatable/js/dataTables.bootstrap4.min.js' %}"></script>
<script>
    $('#datatable').DataTable();
</script>
{% endblock script %}