source/visitormanagement/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.onGetLogin, name='login'),
    path('onPostLogin/', views.onPostLogin, name='onPostLogin'),
    path('logout/', views.onPostLogout, name='logout'),
]

source/visitormanagement/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

source/visitormanagement/visitormanagement/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('visitors/', include('visitors.urls', namespace='visitors')),
    path('companies/', include('companies.urls', namespace='companies')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

source/visitormanagement/visitormanagement/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ settings.APP_NAME }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
    {% block styles %} {% endblock styles %}
</head>
<body class="text-monospace">
<nav class="navbar navbar-light fixed-top bg-white flex-md-nowrap p-0 shadow-sm">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'home:index' %}"><span data-feather="layers"></span> <b>{{ settings.APP_NAME }}</b></a>
  {% include "nav-top.html" %}
</nav>
<div class="container-fluid">
  <div class="row">
    {% include "sidebar.html" %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4 mt-3">
      {% block content %} {% endblock %}
    </main>
  </div>
</div>
<script src="{% static 'lib/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'lib/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/feather.min.js' %}"></script>
<script src="{% static 'js/dashboard.js'%}"></script>
<script src="{% static 'js/validate.js'%}"></script>
<script>
  setTimeout(function () {
     $('.message-span').html(null);
  }, 3000);
</script>
{% block script %} {% endblock script %}
</body>
</html>

source/visitormanagement/visitormanagement/templates/nav-top.html
{% if user.is_authenticated %}
<ul class="navbar-nav mr-auto ml-4">
    <li class="nav-item text-nowrap">
        <a class="text-center alert-toast nav-link" href="#">
            <span style="color:forestgreen;" class="message-span"></span>
        </a>
    </li>
</ul>
<ul class="navbar-nav">
    <li class="nav-item text-nowrap"><a style="color:green" class="nav-link" href="#"><span data-feather="user"></span> <b>{{ user.username }}</b></a></li>
</ul>
<ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap"><a style="color:red" class="nav-link" href="{% url 'accounts:logout' %}"><span data-feather="log-out"></span> <b>logout</b></a></li>
</ul>
{% endif %}

source/visitormanagement/visitormanagement/templates/sidebar.html
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'visitors:index' %}">
              <span data-feather="list"></span> visitors
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>masters</span>
          <a class="d-flex align-items-center text-muted" href="#">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>

        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'companies:index' %}">
              <span data-feather="briefcase"></span> companies
            </a>
          </li>
        </ul>
      </div>
</nav>